//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputSystem/InputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMap"",
    ""maps"": [
        {
            ""name"": ""PlayerInputDefault"",
            ""id"": ""9c32aa5a-139b-41ba-bf60-eeec16ff13ec"",
            ""actions"": [
                {
                    ""name"": ""JumpInput"",
                    ""type"": ""Button"",
                    ""id"": ""d9812f27-6fbc-40d5-9d4c-1985f2d84f54"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GrappleShootInput"",
                    ""type"": ""Button"",
                    ""id"": ""87ba570c-778f-459e-a11a-5fb9fd362370"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GrappleRetractInput"",
                    ""type"": ""Button"",
                    ""id"": ""a2c4fa50-39e4-4f7a-8113-de43a94e598f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GrappleAimInput"",
                    ""type"": ""Value"",
                    ""id"": ""5059688e-cb31-4720-8d22-72a674427ca6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a6fc145f-2e96-4d80-a970-d6fbe34e4572"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fbaa3f19-f09f-4e45-b174-09553bc27423"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0635d48c-b0ad-4144-8037-c63a0e8306aa"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bc21444-42e6-425f-9146-37e07fdfd578"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrappleShootInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24f6e2d5-9a04-4cc3-8641-d6d333534955"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrappleShootInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9632333b-bbdb-43bf-bebe-fd1949fe49f4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrappleRetractInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08f9bd3f-9dcb-40e0-bd4e-89e3afcacb5e"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrappleRetractInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f4d347d-a0a2-4cce-a239-181211758696"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrappleAimInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6701ddce-1f5a-4b2e-94c4-df350ab5a59c"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrappleAimInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInputDefault
        m_PlayerInputDefault = asset.FindActionMap("PlayerInputDefault", throwIfNotFound: true);
        m_PlayerInputDefault_JumpInput = m_PlayerInputDefault.FindAction("JumpInput", throwIfNotFound: true);
        m_PlayerInputDefault_GrappleShootInput = m_PlayerInputDefault.FindAction("GrappleShootInput", throwIfNotFound: true);
        m_PlayerInputDefault_GrappleRetractInput = m_PlayerInputDefault.FindAction("GrappleRetractInput", throwIfNotFound: true);
        m_PlayerInputDefault_GrappleAimInput = m_PlayerInputDefault.FindAction("GrappleAimInput", throwIfNotFound: true);
    }

    ~@InputMap()
    {
        UnityEngine.Debug.Assert(!m_PlayerInputDefault.enabled, "This will cause a leak and performance issues, InputMap.PlayerInputDefault.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInputDefault
    private readonly InputActionMap m_PlayerInputDefault;
    private List<IPlayerInputDefaultActions> m_PlayerInputDefaultActionsCallbackInterfaces = new List<IPlayerInputDefaultActions>();
    private readonly InputAction m_PlayerInputDefault_JumpInput;
    private readonly InputAction m_PlayerInputDefault_GrappleShootInput;
    private readonly InputAction m_PlayerInputDefault_GrappleRetractInput;
    private readonly InputAction m_PlayerInputDefault_GrappleAimInput;
    public struct PlayerInputDefaultActions
    {
        private @InputMap m_Wrapper;
        public PlayerInputDefaultActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @JumpInput => m_Wrapper.m_PlayerInputDefault_JumpInput;
        public InputAction @GrappleShootInput => m_Wrapper.m_PlayerInputDefault_GrappleShootInput;
        public InputAction @GrappleRetractInput => m_Wrapper.m_PlayerInputDefault_GrappleRetractInput;
        public InputAction @GrappleAimInput => m_Wrapper.m_PlayerInputDefault_GrappleAimInput;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInputDefault; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputDefaultActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerInputDefaultActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInputDefaultActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInputDefaultActionsCallbackInterfaces.Add(instance);
            @JumpInput.started += instance.OnJumpInput;
            @JumpInput.performed += instance.OnJumpInput;
            @JumpInput.canceled += instance.OnJumpInput;
            @GrappleShootInput.started += instance.OnGrappleShootInput;
            @GrappleShootInput.performed += instance.OnGrappleShootInput;
            @GrappleShootInput.canceled += instance.OnGrappleShootInput;
            @GrappleRetractInput.started += instance.OnGrappleRetractInput;
            @GrappleRetractInput.performed += instance.OnGrappleRetractInput;
            @GrappleRetractInput.canceled += instance.OnGrappleRetractInput;
            @GrappleAimInput.started += instance.OnGrappleAimInput;
            @GrappleAimInput.performed += instance.OnGrappleAimInput;
            @GrappleAimInput.canceled += instance.OnGrappleAimInput;
        }

        private void UnregisterCallbacks(IPlayerInputDefaultActions instance)
        {
            @JumpInput.started -= instance.OnJumpInput;
            @JumpInput.performed -= instance.OnJumpInput;
            @JumpInput.canceled -= instance.OnJumpInput;
            @GrappleShootInput.started -= instance.OnGrappleShootInput;
            @GrappleShootInput.performed -= instance.OnGrappleShootInput;
            @GrappleShootInput.canceled -= instance.OnGrappleShootInput;
            @GrappleRetractInput.started -= instance.OnGrappleRetractInput;
            @GrappleRetractInput.performed -= instance.OnGrappleRetractInput;
            @GrappleRetractInput.canceled -= instance.OnGrappleRetractInput;
            @GrappleAimInput.started -= instance.OnGrappleAimInput;
            @GrappleAimInput.performed -= instance.OnGrappleAimInput;
            @GrappleAimInput.canceled -= instance.OnGrappleAimInput;
        }

        public void RemoveCallbacks(IPlayerInputDefaultActions instance)
        {
            if (m_Wrapper.m_PlayerInputDefaultActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerInputDefaultActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInputDefaultActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInputDefaultActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerInputDefaultActions @PlayerInputDefault => new PlayerInputDefaultActions(this);
    public interface IPlayerInputDefaultActions
    {
        void OnJumpInput(InputAction.CallbackContext context);
        void OnGrappleShootInput(InputAction.CallbackContext context);
        void OnGrappleRetractInput(InputAction.CallbackContext context);
        void OnGrappleAimInput(InputAction.CallbackContext context);
    }
}
